language: node_js
node_js:
  - '8'
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install --prefix
  - npm run build --prefix
script:
  - nohup npm run start & --prefix
  - sleep 3
  - npm run test --prefix
